version: '3.8'

services:

  db:
    container_name: db_autoservice
    image: library/postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autoservice
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build:
      context: .
      dockerfile: docker/services/app/Dockerfile
    container_name: app_autoservice
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/autoservice
      - SPRING_DATASOURSE_USERNAME=postgres
      - SPRING_DATASOURSE_PASSWORD=postgres
      - SPRING_DATASOURSE_HIKARI_SCHEMA=autoservice
      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=true
      - SPRING_FLYWAY_ENABLED=true
    ports:
      - "8181:8181"
    depends_on:
      - db

  keycloak:
    image: jboss/keycloak
    container_name: keycloak_autoservice
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: autoservice
      DB_SCHEMA: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 1
    ports:
      - "8484:8484"
    depends_on:
      - app
    links:
      - "db:db"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - keycloak

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    hostname: http://loki.default.svc.cluster.local
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - grafana

volumes:
  db-data:
  grafana-postgres:
  prometheus_data: {}
