package ru.cs.vsu.autoservice.model.enums;

public enum PartTypeEnum {

    ENGINE, FUEL_SYSTEM, EXHAUST_SYSTEM_AND_COOLING, ENGINE_ELECTRICAL,
    BODY_ELECTRICAL, TRANSMISSION, CHASSIS, BRAKE_SYSTEM, STEERING,
    BODY_DETAILS, INTERIOR_DETAILS

}
